Repository tazama-lf/transaction-aggregation-decisioning-processor, pull requests merged in 2024-10, with the labels that each got.

#226 feat: Env/validation
  .env.template
  Dockerfile
  __tests__/unit/logic.service.test.ts
  __tests__/unit/typology.helper.test.ts
  package-lock.json
  package.json
  src/apm.ts
  src/config.ts
  src/index.ts
Labels: enhancement

#231 refactor: Split cache options
  .env.template
  Dockerfile
  __tests__/unit/logic.service.test.ts
  __tests__/unit/typology.helper.test.ts
  package-lock.json
  package.json
  src/config.ts
Labels: refactor

#233 build: remove unused deps
  package-lock.json
  package.json
Labels: build

#237 refactor: encapsulate service creation to lib
  .env.template
  Dockerfile
  __tests__/unit/logic.service.test.ts
  __tests__/unit/typology.helper.test.ts
  cluster-setup.ts
  package-lock.json
  package.json
  src/apm.ts
  src/config.ts
  src/index.ts
  src/services/helper.service.ts
  src/services/logic.service.ts
  src/services/services.ts
Labels: refactor
